//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
// Zen Spaces
//
// Copyright (C) 2001 - 2009 Tony Richards
//
// Licensed under the Games by Sarge Publishing License - See your licensing
// agreement for terms and conditions.
//
// Do not redistribute this source code.
//
// Tony Richards trichards@gamesbysarge.com
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
// This is generated by the Zen Spaces Code Generator.  Do not modify!
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
#ifndef ZEN_COMMUNITY_CHAT_ALLOWUSER_DATA_COLLECTION_HPP_INCLUDED
#define ZEN_COMMUNITY_CHAT_ALLOWUSER_DATA_COLLECTION_HPP_INCLUDED

#include "../I_AllowUserDataCollection.hpp"

#include <list>

//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
namespace Zen {
namespace Community {
namespace Chat {
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~


class AllowUserDataCollection
:	public I_AllowUserDataCollection
{
    /// @name I_AllowUserDataCollection implementation.
    /// @{
public:
    virtual void push_back(pAllowUserDomainObject_type _pDomainObject);
    virtual void getAll(I_CollectionVisitor& _visitor);
    virtual bool isEmpty() const;
    /// @}

    /// @name 'Structors
    /// @{
public:
             AllowUserDataCollection();
    virtual ~AllowUserDataCollection();
    /// @}

    /// @name Member Variables
    /// @{
private:
    typedef std::list<pAllowUserDomainObject_type>  Collection_type;
    Collection_type                                     m_objects;
    /// @}
    
};  // class AllowUserDataCollection

//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
}   // namespace Zen
}   // namespace Community
}   // namespace Chat
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~


#endif // ZEN_COMMUNITY_CHAT_ALLOWUSER_DATA_COLLECTION_HPP_INCLUDED
