//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
// Zen Spaces
//
// Copyright (C) 2001 - 2009 Tony Richards
//
// Licensed under the Games by Sarge Publishing License - See your licensing
// agreement for terms and conditions.
//
// Do not redistribute this source code.
//
// Tony Richards trichards@gamesbysarge.com
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
// This is generated by the Zen Spaces Code Generator.  Do not modify!
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
#include "ChatLogDomainObject.hpp"

#include <Zen/Core/Utility/runtime_exception.hpp>

//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
namespace Zen {
namespace Community {
namespace Chat {
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~

ChatLogDomainObject::ChatLogDomainObject()
{
    m_elements["chatLogId"] = m_pChatLogId = Zen::Enterprise::DataModel::I_DataElement::create();
    m_elements["channelId"] = m_pChannelId = Zen::Enterprise::DataModel::I_DataElement::create();
    m_elements["accountId"] = m_pAccountId = Zen::Enterprise::DataModel::I_DataElement::create();
    m_elements["messageType"] = m_pMessageType = Zen::Enterprise::DataModel::I_DataElement::create();
    m_elements["message"] = m_pMessage = Zen::Enterprise::DataModel::I_DataElement::create();
    m_elements["logTime"] = m_pLogTime = Zen::Enterprise::DataModel::I_DataElement::create();
}

//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
ChatLogDomainObject::~ChatLogDomainObject()
{
}

//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
ChatLogDomainObject::ElementReference_type
ChatLogDomainObject::getChatLogId() const
{
    return *m_pChatLogId.get();
}

//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
void
ChatLogDomainObject::setChatLogId(const boost::any& _value)
{
    m_pChatLogId->setAnyValue(_value);
}

//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
ChatLogDomainObject::ElementReference_type
ChatLogDomainObject::getChannelId() const
{
    return *m_pChannelId.get();
}

//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
void
ChatLogDomainObject::setChannelId(const boost::any& _value)
{
    m_pChannelId->setAnyValue(_value);
}

//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
ChatLogDomainObject::ElementReference_type
ChatLogDomainObject::getAccountId() const
{
    return *m_pAccountId.get();
}

//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
void
ChatLogDomainObject::setAccountId(const boost::any& _value)
{
    m_pAccountId->setAnyValue(_value);
}

//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
ChatLogDomainObject::ElementReference_type
ChatLogDomainObject::getMessageType() const
{
    return *m_pMessageType.get();
}

//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
void
ChatLogDomainObject::setMessageType(const boost::any& _value)
{
    m_pMessageType->setAnyValue(_value);
}

//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
ChatLogDomainObject::ElementReference_type
ChatLogDomainObject::getMessage() const
{
    return *m_pMessage.get();
}

//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
void
ChatLogDomainObject::setMessage(const boost::any& _value)
{
    m_pMessage->setAnyValue(_value);
}

//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
ChatLogDomainObject::ElementReference_type
ChatLogDomainObject::getLogTime() const
{
    return *m_pLogTime.get();
}

//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
void
ChatLogDomainObject::setLogTime(const boost::any& _value)
{
    m_pLogTime->setAnyValue(_value);
}

//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
Zen::Enterprise::DataModel::I_DataElement&
ChatLogDomainObject::getElement(const std::string& _fieldName)
{
    // TODO Guard?

    FieldElementMap_type::iterator iter = m_elements.find(_fieldName);
    if (iter != m_elements.end())
    {
        return *iter->second;
    }
    else
    {
        pElement_type pElement = Zen::Enterprise::DataModel::I_DataElement::create();
        m_elements[_fieldName] = pElement;

        return *pElement;
    }
}

//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
}   // namespace Zen
}   // namespace Community
}   // namespace Chat
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~

