//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
// Zen Community Framework
//
// Copyright (C) 2001 - 2010 Tony Richards
// Copyright (C) 2008 - 2010 Matthew Alan Gray
//
//  This software is provided 'as-is', without any express or implied
//  warranty.  In no event will the authors be held liable for any damages
//  arising from the use of this software.
//
//  Permission is granted to anyone to use this software for any purpose,
//  including commercial applications, and to alter it and redistribute it
//  freely, subject to the following restrictions:
//
//  1. The origin of this software must not be misrepresented; you must not
//     claim that you wrote the original software. If you use this software
//     in a product, an acknowledgment in the product documentation would be
//     appreciated but is not required.
//  2. Altered source versions must be plainly marked as such, and must not be
//     misrepresented as being the original software.
//  3. This notice may not be removed or altered from any source distribution.
//
//  Tony Richards trichards@indiezen.com
//  Matthew Alan Gray mgray@indiezen.org
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
// This is generated by the Zen Protocol Code Generator.  Do not modify!
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
// Zen Protocol
//
// Copyright (C) 2001 - 2009 Tony Richards
//
// Licensed under the Games by Sarge Publishing License - See your licensing
// agreement for terms and conditions.
//
// Do not redistribute this source code.
//
// Tony Richards trichards@gamesbysarge.com
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
// This is generated by the Zen Protocol Code Generator.  Do not modify!
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
#include "ChatProtocolManager.hpp"

#include "CreateChannelRequest.hpp"
#include "CreateChannelResponse.hpp"

#include "UnsubscribeChannelModelRequest.hpp"
#include "UnsubscribeChannelModelResponse.hpp"

#include "DeleteChannelRequest.hpp"
#include "DeleteChannelResponse.hpp"

#include "UpdateChannelRequest.hpp"
#include "UpdateChannelResponse.hpp"

#include "ReadChannelRequest.hpp"
#include "ReadChannelResponse.hpp"

#include "JoinChannelRequest.hpp"
#include "JoinChannelResponse.hpp"

#include "SubscribeChannelModelRequest.hpp"
#include "SubscribeChannelModelResponse.hpp"

#include "ChannelModelUpdateMessage.hpp"

#include <Zen/Enterprise/AppServer/I_ApplicationServer.hpp>
#include <Zen/Enterprise/AppServer/I_MessageHeader.hpp>

#include <Zen/Enterprise/Networking/I_Endpoint.hpp>

//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
namespace Zen {
namespace Community {
namespace Protocol {
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~

ChatProtocolManager::ChatProtocolManager()
{
}

//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
ChatProtocolManager::~ChatProtocolManager()
{
}

//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
void
ChatProtocolManager::install(Zen::Enterprise::AppServer::I_ApplicationServer& _appServer)
{
    if (!m_installed)
    {
        CreateChannelRequest::registerMessage(_appServer);
        CreateChannelResponse::registerMessage(_appServer);

        UnsubscribeChannelModelRequest::registerMessage(_appServer);
        UnsubscribeChannelModelResponse::registerMessage(_appServer);

        DeleteChannelRequest::registerMessage(_appServer);
        DeleteChannelResponse::registerMessage(_appServer);

        UpdateChannelRequest::registerMessage(_appServer);
        UpdateChannelResponse::registerMessage(_appServer);

        ReadChannelRequest::registerMessage(_appServer);
        ReadChannelResponse::registerMessage(_appServer);

        JoinChannelRequest::registerMessage(_appServer);
        JoinChannelResponse::registerMessage(_appServer);

        SubscribeChannelModelRequest::registerMessage(_appServer);
        SubscribeChannelModelResponse::registerMessage(_appServer);

        ChannelModelUpdateMessage::registerMessage(_appServer);

        m_installed = true;
    }
}
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
}   // namespace Zen
}   // namespace Community
}   // namespace Protocol
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~

