//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
// Zen Spaces
//
// Copyright (C) 2001 - 2009 Tony Richards
//
// Licensed under the Games by Sarge Publishing License - See your licensing
// agreement for terms and conditions.
//
// Do not redistribute this source code.
//
// Tony Richards trichards@gamesbysarge.com
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
// This is generated by the Zen Spaces Code Generator.  Do not modify!
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
#ifndef GAMEBUILDER_I_GAMEOBJECTELEMENT_DOMAIN_OBJECT_HPP_INCLUDED
#define GAMEBUILDER_I_GAMEOBJECTELEMENT_DOMAIN_OBJECT_HPP_INCLUDED

#include "Configuration.hpp"

#include <Zen/Core/Memory/managed_ptr.hpp>

#include <Zen/Enterprise/DataModel/I_DataElement.hpp>

#include <boost/noncopyable.hpp>
#include <boost/any.hpp>

//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
namespace GameBuilder {
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~


class GAMEBUILDERMODEL_DLL_LINK I_GameObjectElementDomainObject
:	public boost::noncopyable
{
    /// @name Types
    /// @{
public:
    typedef Zen::Memory::managed_ptr<Zen::Enterprise::DataModel::I_DataElement> pElement_type;
    typedef Zen::Enterprise::DataModel::I_DataElement&                          ElementReference_type;
    /// @}

    /// @name Getter / Setter methods
    /// @{
public:
    /// Get the GameObjectElementId element.
    /// Use this return value to check to see if the column is NULL in the database,
    /// or you can use it to modify the value instead of calling setGameObjectElementId().
    virtual ElementReference_type getGameObjectElementId() const = 0;
    
    /// Set the GameObjectElementId element value.
    /// This method does not directly update the database.  
    /// You must use the I_GameObjectElementDataMap::update() method for the modifications
    /// to be persisted.
    virtual void setGameObjectElementId(const boost::any& _value) = 0;

    /// Get the GameObjectTypeId element.
    /// Use this return value to check to see if the column is NULL in the database,
    /// or you can use it to modify the value instead of calling setGameObjectTypeId().
    virtual ElementReference_type getGameObjectTypeId() const = 0;
    
    /// Set the GameObjectTypeId element value.
    /// This method does not directly update the database.  
    /// You must use the I_GameObjectElementDataMap::update() method for the modifications
    /// to be persisted.
    virtual void setGameObjectTypeId(const boost::any& _value) = 0;

    /// Get the OverrideParent element.
    /// Use this return value to check to see if the column is NULL in the database,
    /// or you can use it to modify the value instead of calling setOverrideParent().
    virtual ElementReference_type getOverrideParent() const = 0;
    
    /// Set the OverrideParent element value.
    /// This method does not directly update the database.  
    /// You must use the I_GameObjectElementDataMap::update() method for the modifications
    /// to be persisted.
    virtual void setOverrideParent(const boost::any& _value) = 0;

    /// Get the SequenceNumber element.
    /// Use this return value to check to see if the column is NULL in the database,
    /// or you can use it to modify the value instead of calling setSequenceNumber().
    virtual ElementReference_type getSequenceNumber() const = 0;
    
    /// Set the SequenceNumber element value.
    /// This method does not directly update the database.  
    /// You must use the I_GameObjectElementDataMap::update() method for the modifications
    /// to be persisted.
    virtual void setSequenceNumber(const boost::any& _value) = 0;

    /// Get the Name element.
    /// Use this return value to check to see if the column is NULL in the database,
    /// or you can use it to modify the value instead of calling setName().
    virtual ElementReference_type getName() const = 0;
    
    /// Set the Name element value.
    /// This method does not directly update the database.  
    /// You must use the I_GameObjectElementDataMap::update() method for the modifications
    /// to be persisted.
    virtual void setName(const boost::any& _value) = 0;

    /// Get the DataType element.
    /// Use this return value to check to see if the column is NULL in the database,
    /// or you can use it to modify the value instead of calling setDataType().
    virtual ElementReference_type getDataType() const = 0;
    
    /// Set the DataType element value.
    /// This method does not directly update the database.  
    /// You must use the I_GameObjectElementDataMap::update() method for the modifications
    /// to be persisted.
    virtual void setDataType(const boost::any& _value) = 0;

    /// Get the DefaultValue element.
    /// Use this return value to check to see if the column is NULL in the database,
    /// or you can use it to modify the value instead of calling setDefaultValue().
    virtual ElementReference_type getDefaultValue() const = 0;
    
    /// Set the DefaultValue element value.
    /// This method does not directly update the database.  
    /// You must use the I_GameObjectElementDataMap::update() method for the modifications
    /// to be persisted.
    virtual void setDefaultValue(const boost::any& _value) = 0;

    /// Get the PropertiesId element.
    /// Use this return value to check to see if the column is NULL in the database,
    /// or you can use it to modify the value instead of calling setPropertiesId().
    virtual ElementReference_type getPropertiesId() const = 0;
    
    /// Set the PropertiesId element value.
    /// This method does not directly update the database.  
    /// You must use the I_GameObjectElementDataMap::update() method for the modifications
    /// to be persisted.
    virtual void setPropertiesId(const boost::any& _value) = 0;
    
    virtual Zen::Enterprise::DataModel::I_DataElement& getElement(const std::string& _fieldName) = 0;
    /// @}

    /// @name 'Structors
    /// @{
protected:
             I_GameObjectElementDomainObject();
    virtual ~I_GameObjectElementDomainObject();
    /// @}

};  // interface I_GameObjectElementDomainObject

//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
}   // namespace GameBuilder
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~

namespace Zen {
namespace Memory {
    /// I_GameObjectElementDomainObject is a managed by factory
    template<>
    struct is_managed_by_factory<GameBuilder::I_GameObjectElementDomainObject> : public boost::true_type{};
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
}   // namespace Memory
}   // namespace Zen
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~

#endif // GAMEBUILDER_I_GAMEOBJECTELEMENT_DOMAIN_OBJECT_HPP_INCLUDED
