//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
// Zen Spaces
//
// Copyright (C) 2001 - 2009 Tony Richards
//
// Licensed under the Games by Sarge Publishing License - See your licensing
// agreement for terms and conditions.
//
// Do not redistribute this source code.
//
// Tony Richards trichards@gamesbysarge.com
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
// This is generated by the Zen Spaces Code Generator.  Do not modify!
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
#ifndef ZEN_COMMUNITY_SESSION_I_ACCOUNT_DATA_MAP_HPP_INCLUDED
#define ZEN_COMMUNITY_SESSION_I_ACCOUNT_DATA_MAP_HPP_INCLUDED

#include "Configuration.hpp"

#include <Zen/Core/Memory/managed_ptr.hpp>

#include <Zen/Enterprise/Database/I_DatabaseConnection.hpp>
#include <Zen/Enterprise/Database/I_DatabaseService.hpp>
#include <Zen/Enterprise/Database/I_DatabaseTransaction.hpp>

#include <boost/cstdint.hpp>

#include <boost/noncopyable.hpp>

//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
namespace Zen {
namespace Community {
namespace Session {
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~

class I_AccountDomainObject;
class I_AccountDataCollection;

class SESSIONMODEL_DLL_LINK I_AccountDataMap
:	public boost::noncopyable
{

    /// @name Types
    /// @{
public:
//    typedef Zen::Memory::managed_ptr<I_AccountDomainObject>   pAccountDomainObject_type;
//    typedef Zen::Memory::managed_ptr<I_AccountDataCollection>     pAccountDataCollection_type;
    typedef Zen::Memory::managed_ptr<I_AccountDataMap>        pAccountDataMap_type;

    typedef Zen::Database::I_DatabaseService::pDatabaseConnection_type      pDatabaseConnection_type;

    typedef Zen::Memory::managed_ptr<I_AccountDataCollection>  pAccountDataCollection_type;
    typedef Zen::Event::future_return_value<pAccountDataCollection_type>  FutureAccountDataCollection_type;
	typedef Zen::Memory::managed_ptr<FutureAccountDataCollection_type>    pFutureAccountDataCollection_type;
    
    typedef Zen::Memory::managed_ptr<I_AccountDomainObject>  pAccountDomainObject_type;
    typedef Zen::Event::future_return_value<pAccountDomainObject_type>  FutureAccountDomainObject_type;
	typedef Zen::Memory::managed_ptr<FutureAccountDomainObject_type>    pFutureAccountDomainObject_type;
    /// @}

    /// @name I_AccountDataMap interface
    /// @{
public:
    /// Create a new AccountDomainObject.
    virtual pAccountDomainObject_type createNew() = 0;
    
    /// Get an object by primary key.
    virtual pFutureAccountDomainObject_type getByKey(boost::uint64_t _primaryKeyValue) = 0;

    /// Delete an object by primary key.
    virtual void deleteByKey(boost::uint64_t _primaryKeyValue) = 0;

    /// Get a collection of Account by user and password.    
    virtual pFutureAccountDataCollection_type getByUserPassword(const std::string& _user, const std::string& _password) = 0;

    /// Get all of the records.
    virtual pFutureAccountDataCollection_type getAll() = 0;

    /// Update a AccountDomainObject.
    /// If the AccountDomainObject hasn't been inserted yet, it will be inserted.
    virtual Zen::Database::I_DatabaseTransaction::pFutureKey_type update(pAccountDomainObject_type _pAccountDomainObject) = 0;
    /// @}

    /// @name Static class factory
    /// @{
public:
    static pAccountDataMap_type create(pDatabaseConnection_type _pDatabaseConnection);
    /// @}

    /// @name 'Structors
    /// @{
protected:
             I_AccountDataMap();
    virtual ~I_AccountDataMap();
    /// @}

};  // interface I_AccountDataMap

//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
}   // namespace Zen
}   // namespace Community
}   // namespace Session
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~

namespace Zen {
namespace Memory {
    /// I_AccountDataMap is a managed by factory
    template<>
    struct is_managed_by_factory<Zen::Community::Session::I_AccountDataMap> : public boost::true_type{};
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
}   // namespace Memory
}   // namespace Zen
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~

#endif // ZEN_COMMUNITY_SESSION_I_ACCOUNT_DATA_MAP_HPP_INCLUDED
