//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
// Zen Community Framework
//
// Copyright (C) 2001 - 2010 Tony Richards
// Copyright (C) 2008 - 2010 Matthew Alan Gray
//
//  This software is provided 'as-is', without any express or implied
//  warranty.  In no event will the authors be held liable for any damages
//  arising from the use of this software.
//
//  Permission is granted to anyone to use this software for any purpose,
//  including commercial applications, and to alter it and redistribute it
//  freely, subject to the following restrictions:
//
//  1. The origin of this software must not be misrepresented; you must not
//     claim that you wrote the original software. If you use this software
//     in a product, an acknowledgment in the product documentation would be
//     appreciated but is not required.
//  2. Altered source versions must be plainly marked as such, and must not be
//     misrepresented as being the original software.
//  3. This notice may not be removed or altered from any source distribution.
//
//  Tony Richards trichards@indiezen.com
//  Matthew Alan Gray mgray@indiezen.org
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
// This is generated by the Zen Protocol Code Generator.  Do not modify!
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
// Zen Protocol
//
// Copyright (C) 2001 - 2009 Tony Richards
//
// Licensed under the Games by Sarge Publishing License - See your licensing
// agreement for terms and conditions.
//
// Do not redistribute this source code.
//
// Tony Richards trichards@gamesbysarge.com
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
// This is generated by the Zen Protocol Code Generator.  Do not modify!
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
#include "AccountProtocolManager.hpp"

#include "UnsubscribeAccountModelRequest.hpp"
#include "UnsubscribeAccountModelResponse.hpp"

#include "UpdateGroupRequest.hpp"
#include "UpdateGroupResponse.hpp"

#include "DeleteAccountRequest.hpp"
#include "DeleteAccountResponse.hpp"

#include "CreateAccountRequest.hpp"
#include "CreateAccountResponse.hpp"

#include "SubscribeGroupModelRequest.hpp"
#include "SubscribeGroupModelResponse.hpp"

#include "UnsubscribeGroupModelRequest.hpp"
#include "UnsubscribeGroupModelResponse.hpp"

#include "ReadAccountRequest.hpp"
#include "ReadAccountResponse.hpp"

#include "UpdateAccountRequest.hpp"
#include "UpdateAccountResponse.hpp"

#include "SubscribeAccountModelRequest.hpp"
#include "SubscribeAccountModelResponse.hpp"

#include "CreateGroupRequest.hpp"
#include "CreateGroupResponse.hpp"

#include "DeleteGroupRequest.hpp"
#include "DeleteGroupResponse.hpp"

#include "ReadGroupRequest.hpp"
#include "ReadGroupResponse.hpp"

#include "GroupModelUpdateMessage.hpp"
#include "AccountModelUpdateMessage.hpp"

#include <Zen/Enterprise/AppServer/I_ApplicationServer.hpp>
#include <Zen/Enterprise/AppServer/I_MessageHeader.hpp>

#include <Zen/Enterprise/Networking/I_Endpoint.hpp>

//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
namespace Zen {
namespace Community {
namespace Protocol {
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~

AccountProtocolManager::AccountProtocolManager()
{
}

//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
AccountProtocolManager::~AccountProtocolManager()
{
}

//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
void
AccountProtocolManager::install(Zen::Enterprise::AppServer::I_ApplicationServer& _appServer)
{
    if (!m_installed)
    {
        UnsubscribeAccountModelRequest::registerMessage(_appServer);
        UnsubscribeAccountModelResponse::registerMessage(_appServer);

        UpdateGroupRequest::registerMessage(_appServer);
        UpdateGroupResponse::registerMessage(_appServer);

        DeleteAccountRequest::registerMessage(_appServer);
        DeleteAccountResponse::registerMessage(_appServer);

        CreateAccountRequest::registerMessage(_appServer);
        CreateAccountResponse::registerMessage(_appServer);

        SubscribeGroupModelRequest::registerMessage(_appServer);
        SubscribeGroupModelResponse::registerMessage(_appServer);

        UnsubscribeGroupModelRequest::registerMessage(_appServer);
        UnsubscribeGroupModelResponse::registerMessage(_appServer);

        ReadAccountRequest::registerMessage(_appServer);
        ReadAccountResponse::registerMessage(_appServer);

        UpdateAccountRequest::registerMessage(_appServer);
        UpdateAccountResponse::registerMessage(_appServer);

        SubscribeAccountModelRequest::registerMessage(_appServer);
        SubscribeAccountModelResponse::registerMessage(_appServer);

        CreateGroupRequest::registerMessage(_appServer);
        CreateGroupResponse::registerMessage(_appServer);

        DeleteGroupRequest::registerMessage(_appServer);
        DeleteGroupResponse::registerMessage(_appServer);

        ReadGroupRequest::registerMessage(_appServer);
        ReadGroupResponse::registerMessage(_appServer);

        GroupModelUpdateMessage::registerMessage(_appServer);

        AccountModelUpdateMessage::registerMessage(_appServer);

        m_installed = true;
    }
}
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
}   // namespace Zen
}   // namespace Community
}   // namespace Protocol
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~

