//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
// Zen Spaces
//
// Copyright (C) 2001 - 2009 Tony Richards
//
// Licensed under the Games by Sarge Publishing License - See your licensing
// agreement for terms and conditions.
//
// Do not redistribute this source code.
//
// Tony Richards trichards@gamesbysarge.com
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
// This is generated by the Zen Spaces Code Generator.  Do not modify!
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
#ifndef WORLDBUILDER_ZONE_DATA_COLLECTION_HPP_INCLUDED
#define WORLDBUILDER_ZONE_DATA_COLLECTION_HPP_INCLUDED

#include "../I_ZoneDataCollection.hpp"

#include <list>

//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
namespace WorldBuilder {
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~


class ZoneDataCollection
:	public I_ZoneDataCollection
{
    /// @name I_ZoneDataCollection implementation.
    /// @{
public:
    virtual void push_back(pZoneDomainObject_type _pDomainObject);
    virtual void getAll(I_CollectionVisitor& _visitor);
    virtual bool isEmpty() const;
    /// @}

    /// @name 'Structors
    /// @{
public:
             ZoneDataCollection();
    virtual ~ZoneDataCollection();
    /// @}

    /// @name Member Variables
    /// @{
private:
    typedef std::list<pZoneDomainObject_type>  Collection_type;
    Collection_type                                     m_objects;
    /// @}
    
};  // class ZoneDataCollection

//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
}   // namespace WorldBuilder
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~


#endif // WORLDBUILDER_ZONE_DATA_COLLECTION_HPP_INCLUDED
