//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
// Zen Spaces
//
// Copyright (C) 2001 - 2009 Tony Richards
//
// Licensed under the Games by Sarge Publishing License - See your licensing
// agreement for terms and conditions.
//
// Do not redistribute this source code.
//
// Tony Richards trichards@gamesbysarge.com
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
// This is generated by the Zen Spaces Code Generator.  Do not modify!
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
#ifndef ZEN_COMMUNITY_CHAT_I_ALLOWGROUP_DATA_MAP_HPP_INCLUDED
#define ZEN_COMMUNITY_CHAT_I_ALLOWGROUP_DATA_MAP_HPP_INCLUDED

#include "Configuration.hpp"

#include <Zen/Core/Memory/managed_ptr.hpp>

#include <Zen/Enterprise/Database/I_DatabaseConnection.hpp>
#include <Zen/Enterprise/Database/I_DatabaseService.hpp>
#include <Zen/Enterprise/Database/I_DatabaseTransaction.hpp>

#include <boost/cstdint.hpp>
#include <Zen/Community/AccountCommon/I_Group.hpp>
#include <Zen/Community/ChatCommon/I_Channel.hpp>

#include <boost/noncopyable.hpp>

//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
namespace Zen {
namespace Community {
namespace Chat {
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~

class I_AllowGroupDomainObject;
class I_AllowGroupDataCollection;

class CHATMODEL_DLL_LINK I_AllowGroupDataMap
:	public boost::noncopyable
{

    /// @name Types
    /// @{
public:
//    typedef Zen::Memory::managed_ptr<I_AllowGroupDomainObject>   pAllowGroupDomainObject_type;
//    typedef Zen::Memory::managed_ptr<I_AllowGroupDataCollection>     pAllowGroupDataCollection_type;
    typedef Zen::Memory::managed_ptr<I_AllowGroupDataMap>        pAllowGroupDataMap_type;

    typedef Zen::Database::I_DatabaseService::pDatabaseConnection_type      pDatabaseConnection_type;

    typedef Zen::Memory::managed_ptr<I_AllowGroupDataCollection>  pAllowGroupDataCollection_type;
    typedef Zen::Event::future_return_value<pAllowGroupDataCollection_type>  FutureAllowGroupDataCollection_type;
	typedef Zen::Memory::managed_ptr<FutureAllowGroupDataCollection_type>    pFutureAllowGroupDataCollection_type;
    
    typedef Zen::Memory::managed_ptr<I_AllowGroupDomainObject>  pAllowGroupDomainObject_type;
    typedef Zen::Event::future_return_value<pAllowGroupDomainObject_type>  FutureAllowGroupDomainObject_type;
	typedef Zen::Memory::managed_ptr<FutureAllowGroupDomainObject_type>    pFutureAllowGroupDomainObject_type;
    /// @}

    /// @name I_AllowGroupDataMap interface
    /// @{
public:
    /// Create a new AllowGroupDomainObject.
    virtual pAllowGroupDomainObject_type createNew() = 0;
    
    /// Get an object by primary key.
    virtual pFutureAllowGroupDomainObject_type getByKey(boost::uint64_t _primaryKeyValue) = 0;

    /// Delete an object by primary key.
    virtual void deleteByKey(boost::uint64_t _primaryKeyValue) = 0;

    /// Get a collection of allowed groups by channel.    
    virtual pFutureAllowGroupDataCollection_type getByChannel(Common::I_Channel& _channel) = 0;

    /// Get a collection of channels a group is allowed to access.    
    virtual pFutureAllowGroupDataCollection_type getByGroup(Common::I_Group& _group) = 0;

    /// Get all of the records.
    virtual pFutureAllowGroupDataCollection_type getAll() = 0;

    /// Update a AllowGroupDomainObject.
    /// If the AllowGroupDomainObject hasn't been inserted yet, it will be inserted.
    virtual Zen::Database::I_DatabaseTransaction::pFutureKey_type update(pAllowGroupDomainObject_type _pAllowGroupDomainObject) = 0;
    /// @}

    /// @name Static class factory
    /// @{
public:
    static pAllowGroupDataMap_type create(pDatabaseConnection_type _pDatabaseConnection);
    /// @}

    /// @name 'Structors
    /// @{
protected:
             I_AllowGroupDataMap();
    virtual ~I_AllowGroupDataMap();
    /// @}

};  // interface I_AllowGroupDataMap

//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
}   // namespace Zen
}   // namespace Community
}   // namespace Chat
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~

namespace Zen {
namespace Memory {
    /// I_AllowGroupDataMap is a managed by factory
    template<>
    struct is_managed_by_factory<Zen::Community::Chat::I_AllowGroupDataMap> : public boost::true_type{};
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
}   // namespace Memory
}   // namespace Zen
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~

#endif // ZEN_COMMUNITY_CHAT_I_ALLOWGROUP_DATA_MAP_HPP_INCLUDED
