//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
// Zen Spaces
//
// Copyright (C) 2001 - 2009 Tony Richards
//
// Licensed under the Games by Sarge Publishing License - See your licensing
// agreement for terms and conditions.
//
// Do not redistribute this source code.
//
// Tony Richards trichards@gamesbysarge.com
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
// This is generated by the Zen Spaces Code Generator.  Do not modify!
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
#ifndef ZEN_COMMUNITY_CHAT_I_CHATLOG_DATA_MAP_HPP_INCLUDED
#define ZEN_COMMUNITY_CHAT_I_CHATLOG_DATA_MAP_HPP_INCLUDED

#include "Configuration.hpp"

#include <Zen/Core/Memory/managed_ptr.hpp>

#include <Zen/Enterprise/Database/I_DatabaseConnection.hpp>
#include <Zen/Enterprise/Database/I_DatabaseService.hpp>
#include <Zen/Enterprise/Database/I_DatabaseTransaction.hpp>

#include <boost/cstdint.hpp>

#include <boost/noncopyable.hpp>

//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
namespace Zen {
namespace Community {
namespace Chat {
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~

class I_ChatLogDomainObject;
class I_ChatLogDataCollection;

class CHATMODEL_DLL_LINK I_ChatLogDataMap
:	public boost::noncopyable
{

    /// @name Types
    /// @{
public:
//    typedef Zen::Memory::managed_ptr<I_ChatLogDomainObject>   pChatLogDomainObject_type;
//    typedef Zen::Memory::managed_ptr<I_ChatLogDataCollection>     pChatLogDataCollection_type;
    typedef Zen::Memory::managed_ptr<I_ChatLogDataMap>        pChatLogDataMap_type;

    typedef Zen::Database::I_DatabaseService::pDatabaseConnection_type      pDatabaseConnection_type;

    typedef Zen::Memory::managed_ptr<I_ChatLogDataCollection>  pChatLogDataCollection_type;
    typedef Zen::Event::future_return_value<pChatLogDataCollection_type>  FutureChatLogDataCollection_type;
	typedef Zen::Memory::managed_ptr<FutureChatLogDataCollection_type>    pFutureChatLogDataCollection_type;
    
    typedef Zen::Memory::managed_ptr<I_ChatLogDomainObject>  pChatLogDomainObject_type;
    typedef Zen::Event::future_return_value<pChatLogDomainObject_type>  FutureChatLogDomainObject_type;
	typedef Zen::Memory::managed_ptr<FutureChatLogDomainObject_type>    pFutureChatLogDomainObject_type;
    /// @}

    /// @name I_ChatLogDataMap interface
    /// @{
public:
    /// Create a new ChatLogDomainObject.
    virtual pChatLogDomainObject_type createNew() = 0;
    
    /// Get an object by primary key.
    virtual pFutureChatLogDomainObject_type getByKey(boost::uint64_t _primaryKeyValue) = 0;

    /// Delete an object by primary key.
    virtual void deleteByKey(boost::uint64_t _primaryKeyValue) = 0;

    /// Get all of the records.
    virtual pFutureChatLogDataCollection_type getAll() = 0;

    /// Update a ChatLogDomainObject.
    /// If the ChatLogDomainObject hasn't been inserted yet, it will be inserted.
    virtual Zen::Database::I_DatabaseTransaction::pFutureKey_type update(pChatLogDomainObject_type _pChatLogDomainObject) = 0;
    /// @}

    /// @name Static class factory
    /// @{
public:
    static pChatLogDataMap_type create(pDatabaseConnection_type _pDatabaseConnection);
    /// @}

    /// @name 'Structors
    /// @{
protected:
             I_ChatLogDataMap();
    virtual ~I_ChatLogDataMap();
    /// @}

};  // interface I_ChatLogDataMap

//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
}   // namespace Zen
}   // namespace Community
}   // namespace Chat
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~

namespace Zen {
namespace Memory {
    /// I_ChatLogDataMap is a managed by factory
    template<>
    struct is_managed_by_factory<Zen::Community::Chat::I_ChatLogDataMap> : public boost::true_type{};
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
}   // namespace Memory
}   // namespace Zen
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~

#endif // ZEN_COMMUNITY_CHAT_I_CHATLOG_DATA_MAP_HPP_INCLUDED
