//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
// Zen Spaces
//
// Copyright (C) 2001 - 2009 Tony Richards
//
// Licensed under the Games by Sarge Publishing License - See your licensing
// agreement for terms and conditions.
//
// Do not redistribute this source code.
//
// Tony Richards trichards@gamesbysarge.com
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
// This is generated by the Zen Spaces Code Generator.  Do not modify!
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
#ifndef ZEN_COMMUNITY_CHAT_I_CHATCOMMAND_DOMAIN_OBJECT_HPP_INCLUDED
#define ZEN_COMMUNITY_CHAT_I_CHATCOMMAND_DOMAIN_OBJECT_HPP_INCLUDED

#include "Configuration.hpp"

#include <Zen/Core/Memory/managed_ptr.hpp>

#include <Zen/Enterprise/DataModel/I_DataElement.hpp>

#include <boost/noncopyable.hpp>
#include <boost/any.hpp>

//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
namespace Zen {
namespace Community {
namespace Chat {
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~


class CHATMODEL_DLL_LINK I_ChatCommandDomainObject
:	public boost::noncopyable
{
    /// @name Types
    /// @{
public:
    typedef Zen::Memory::managed_ptr<Zen::Enterprise::DataModel::I_DataElement> pElement_type;
    typedef Zen::Enterprise::DataModel::I_DataElement&                          ElementReference_type;
    /// @}

    /// @name Getter / Setter methods
    /// @{
public:
    /// Get the ChatCommandId element.
    /// Use this return value to check to see if the column is NULL in the database,
    /// or you can use it to modify the value instead of calling setChatCommandId().
    virtual ElementReference_type getChatCommandId() const = 0;
    
    /// Set the ChatCommandId element value.
    /// This method does not directly update the database.  
    /// You must use the I_ChatCommandDataMap::update() method for the modifications
    /// to be persisted.
    virtual void setChatCommandId(const boost::any& _value) = 0;

    /// Get the Token element.
    /// Use this return value to check to see if the column is NULL in the database,
    /// or you can use it to modify the value instead of calling setToken().
    virtual ElementReference_type getToken() const = 0;
    
    /// Set the Token element value.
    /// This method does not directly update the database.  
    /// You must use the I_ChatCommandDataMap::update() method for the modifications
    /// to be persisted.
    virtual void setToken(const boost::any& _value) = 0;

    /// Get the Action element.
    /// Use this return value to check to see if the column is NULL in the database,
    /// or you can use it to modify the value instead of calling setAction().
    virtual ElementReference_type getAction() const = 0;
    
    /// Set the Action element value.
    /// This method does not directly update the database.  
    /// You must use the I_ChatCommandDataMap::update() method for the modifications
    /// to be persisted.
    virtual void setAction(const boost::any& _value) = 0;

    /// Get the Response element.
    /// Use this return value to check to see if the column is NULL in the database,
    /// or you can use it to modify the value instead of calling setResponse().
    virtual ElementReference_type getResponse() const = 0;
    
    /// Set the Response element value.
    /// This method does not directly update the database.  
    /// You must use the I_ChatCommandDataMap::update() method for the modifications
    /// to be persisted.
    virtual void setResponse(const boost::any& _value) = 0;

    /// Get the Flags element.
    /// Use this return value to check to see if the column is NULL in the database,
    /// or you can use it to modify the value instead of calling setFlags().
    virtual ElementReference_type getFlags() const = 0;
    
    /// Set the Flags element value.
    /// This method does not directly update the database.  
    /// You must use the I_ChatCommandDataMap::update() method for the modifications
    /// to be persisted.
    virtual void setFlags(const boost::any& _value) = 0;

    /// Get the OwnerId element.
    /// Use this return value to check to see if the column is NULL in the database,
    /// or you can use it to modify the value instead of calling setOwnerId().
    virtual ElementReference_type getOwnerId() const = 0;
    
    /// Set the OwnerId element value.
    /// This method does not directly update the database.  
    /// You must use the I_ChatCommandDataMap::update() method for the modifications
    /// to be persisted.
    virtual void setOwnerId(const boost::any& _value) = 0;

    /// Get the GroupId element.
    /// Use this return value to check to see if the column is NULL in the database,
    /// or you can use it to modify the value instead of calling setGroupId().
    virtual ElementReference_type getGroupId() const = 0;
    
    /// Set the GroupId element value.
    /// This method does not directly update the database.  
    /// You must use the I_ChatCommandDataMap::update() method for the modifications
    /// to be persisted.
    virtual void setGroupId(const boost::any& _value) = 0;
    
    virtual Zen::Enterprise::DataModel::I_DataElement& getElement(const std::string& _fieldName) = 0;
    /// @}

    /// @name 'Structors
    /// @{
protected:
             I_ChatCommandDomainObject();
    virtual ~I_ChatCommandDomainObject();
    /// @}

};  // interface I_ChatCommandDomainObject

//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
}   // namespace Zen
}   // namespace Community
}   // namespace Chat
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~

namespace Zen {
namespace Memory {
    /// I_ChatCommandDomainObject is a managed by factory
    template<>
    struct is_managed_by_factory<Zen::Community::Chat::I_ChatCommandDomainObject> : public boost::true_type{};
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
}   // namespace Memory
}   // namespace Zen
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~

#endif // ZEN_COMMUNITY_CHAT_I_CHATCOMMAND_DOMAIN_OBJECT_HPP_INCLUDED
