//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
// Zen Spaces
//
// Copyright (C) 2001 - 2009 Tony Richards
//
// Licensed under the Games by Sarge Publishing License - See your licensing
// agreement for terms and conditions.
//
// Do not redistribute this source code.
//
// Tony Richards trichards@gamesbysarge.com
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
// This is generated by the Zen Spaces Code Generator.  Do not modify!
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
#ifndef ARTLIBRARY_ARTASSETDOCUMENT_DATA_COLLECTION_HPP_INCLUDED
#define ARTLIBRARY_ARTASSETDOCUMENT_DATA_COLLECTION_HPP_INCLUDED

#include "../I_ArtAssetDocumentDataCollection.hpp"

#include <list>

//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
namespace ArtLibrary {
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~


class ArtAssetDocumentDataCollection
:	public I_ArtAssetDocumentDataCollection
{
    /// @name I_ArtAssetDocumentDataCollection implementation.
    /// @{
public:
    virtual void push_back(pArtAssetDocumentDomainObject_type _pDomainObject);
    virtual void getAll(I_CollectionVisitor& _visitor);
    virtual bool isEmpty() const;
    /// @}

    /// @name 'Structors
    /// @{
public:
             ArtAssetDocumentDataCollection();
    virtual ~ArtAssetDocumentDataCollection();
    /// @}

    /// @name Member Variables
    /// @{
private:
    typedef std::list<pArtAssetDocumentDomainObject_type>  Collection_type;
    Collection_type                                     m_objects;
    /// @}
    
};  // class ArtAssetDocumentDataCollection

//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
}   // namespace ArtLibrary
//-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~


#endif // ARTLIBRARY_ARTASSETDOCUMENT_DATA_COLLECTION_HPP_INCLUDED
